<?php
/**
 * AvsResultCode
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Transactions API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * AvsResultCode Class Doc Comment
 *
 * @category Class
 * @description The result code for the AVS Match.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AvsResultCode
{
    /**
     * Possible values of this enum
     */
    const N = 'N';

    const Y = 'Y';

    const A = 'A';

    const G = 'G';

    const R = 'R';

    const S = 'S';

    const U = 'U';

    const W = 'W';

    const X = 'X';

    const Z = 'Z';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::N,
            self::Y,
            self::A,
            self::G,
            self::R,
            self::S,
            self::U,
            self::W,
            self::X,
            self::Z
        ];
    }
}


