<?php
/**
 * CardType
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Transactions API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * CardType Class Doc Comment
 *
 * @category Class
 * @description The type of card.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CardType
{
    /**
     * Possible values of this enum
     */
    const VISA = 'VISA';

    const MASTERCARD = 'MASTERCARD';

    const AMERICAN_EXPRESS = 'AMERICAN EXPRESS';

    const DISCOVER = 'DISCOVER';

    const DINERS_CLUB = 'DINERS CLUB';

    const JCB = 'JCB';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::VISA,
            self::MASTERCARD,
            self::AMERICAN_EXPRESS,
            self::DISCOVER,
            self::DINERS_CLUB,
            self::JCB
        ];
    }
}


