<?php
/**
 * EmvEntryMethod
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Transactions API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EmvEntryMethod Class Doc Comment
 *
 * @category Class
 * @description The entry method of the card in the EMV Terminal.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class EmvEntryMethod
{
    /**
     * Possible values of this enum
     */
    const DIP = 'EMV_DIP';

    const CONTACTLESS = 'EMV_CONTACTLESS';

    const CONTACTLESS = 'EMV_CONTACTLESS';

    const FALLBACK_NONTECH = 'EMV_FALLBACK_NONTECH';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DIP,
            self::CONTACTLESS,
            self::CONTACTLESS,
            self::FALLBACK_NONTECH
        ];
    }
}


