<?php
/**
 * Type
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Transactions API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * Type Class Doc Comment
 *
 * @category Class
 * @description The transaction type.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Type
{
    /**
     * Possible values of this enum
     */
    const AUTH = 'AUTH';

    const CAPTURE = 'CAPTURE';

    const CARD_INQUIRY = 'CARD INQUIRY';

    const FORCED_SALE = 'FORCED SALE';

    const REFUND = 'REFUND';

    const SALE = 'SALE';

    const VOID = 'VOID';

    const UNMATCHED_REFUND = 'UNMATCHED REFUND';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::AUTH,
            self::CAPTURE,
            self::CARD_INQUIRY,
            self::FORCED_SALE,
            self::REFUND,
            self::SALE,
            self::VOID,
            self::UNMATCHED_REFUND
        ];
    }
}


